export const FETCH_MOVIES_PENDING = "FETCH_MOVIES_PENDING";
export const FETCH_MOVIES_FULFILLED = "FETCH_MOVIES_FULFILLED";
export const FETCH_MOVIES_REJECTED = "FETCH_MOVIES_REJECTED";
export const FETCH_MOVIES_GENRES = "FETCH_MOVIES_GENRES";
export const FETCH_MOVIES_GENRES_BY_ID = "FETCH_MOVIES_GENRES_BY_ID";

export const FETCH_CURRENT_MOVIE_PENDING = "FETCH_CURRENT_MOVIE_PENDING";
export const FETCH_CURRENT_MOVIE_REJECTED = "FETCH_CURRENT_MOVIE_REJECTED";
export const FETCH_CURRENT_MOVIE_FULFILLED = "FETCH_CURRENT_MOVIE_FULFILLED";

export const FETCH_TRAILER_PENDING = "FETCH_TRAILER_PENDING";
export const FETCH_TRAILER_REJECTED = "FETCH_TRAILER_REJECTED";
export const FETCH_TRAILER_FULFILLED = "FETCH_TRAILER_FULFILLED";
export const FETCH_TRAILER_REMOVE = "FETCH_TRAILER_REMOVE";
